---
- name: ensure MySQL is installed
  action: apt pkg={{ item }} state=latest
  with_items:
      - mysql-client
      - mysql-server
  notify : restart mysql

- name: service Mysql is started
  service: name=mysql state=started enabled=yes

- name: set our MySQL config my.cnf
  action: template src='mysqld-ansible.cnf.j2' dest='/etc/mysql/conf.d/mysqld-ansible.cnf'
  notify: restart mysql

- name: create root MySQL users
  mysql_user: name={{ mysql_root_user }} password={{ mysql_root_pass }} host={{ item }} state=present
  with_items:
    - "%"
    - "{{ ansible_eth1.ipv4.address }}"
    - 127.0.0.1
    - ::1
    - localhost
  notify: restart mysql

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: create application MySQL database users
  mysql_user: name={{ mysql_user }} password={{ mysql_pass }} priv={{ mysql_db }}.*:ALL host='{{ item }}' state=present
  with_items:
    - "%"
    - "{{ ansible_eth1.ipv4.address }}"
    - 127.0.0.1
    - ::1
    - localhost
  notify: restart mysql

- name: remove default test MySQL DB
  mysql_db: name=test state=absent